-- Basic kickstart plugins

return {
  -- require 'plugins.harpoon',
  -- require 'plugins.image',
  -- require 'plugins.lazyjj',
  -- require 'plugins.markdown-preview',
  -- require 'plugins.remote',
  -- require 'plugins.render-markdown',
  -- require 'plugins.todone',
  -- require 'plugins.toggleterm',
  -- require 'plugins.vim-visual-multi', -- May be replaced in neovim v0.12+
  require 'plugins.autocompletion',
  require 'plugins.avante',
  require 'plugins.bufferline',
  require 'plugins.comment',
  require 'plugins.conform',
  require 'plugins.debug',
  require 'plugins.diffview',
  require 'plugins.gitsigns',
  require 'plugins.hydra',
  require 'plugins.lspconfig',
  require 'plugins.lualine',
  -- require 'plugins.luarocks',
  require 'plugins.luasnip',
  require 'plugins.markview',
  require 'plugins.mini',
  require 'plugins.neoclip',
  require 'plugins.noice',
  require 'plugins.nvim-colorizer',
  require 'plugins.nvim-lsp-file-op',
  require 'plugins.nvim-tree',
  require 'plugins.outline',
  -- require 'plugins.papis',
  require 'plugins.patterns',
  -- require 'plugins.quarto-nvim',
  require 'plugins.rustaceanvim',
  require 'plugins.slime',
  require 'plugins.snacks',
  require 'plugins.todo-comments',
  require 'plugins.tokyonight',
  require 'plugins.treesitter',
  require 'plugins.trouble',
  require 'plugins.ts-autotag',
  require 'plugins.typst-preview',
  require 'plugins.vimtex',
  require 'plugins.wakatime',
  require 'plugins.wezterm',
  require 'plugins.which-key',
}

-- vim: ts=2 sts=2 sw=2 et
